### ISSUE TITLE
Dockerfile for auditing

### ISSUE THREAD

**Issue by sylvainOL** [rapidfort/community-images#169]
### Name and Version

redis:6.2

### What is the problem this feature will solve?

Hello,

I think the proposition is really interesting but it's hard to have confidence in the solution as the generated Dockerfile is missing.

### What is the feature you are proposing to solve the problem?

Push generated Dockerfile in the repo

### What alternatives have you considered?

N/A I guess

**Comment by codervinod** [comment]
Hi @sylvainOL 

Thanks for the great suggestion, we received this feedback from some other users as well. Our team is working on adding this function to the hardening process. Once the feature is developed, we will integrate it with Community Images.

Meanwhile, please feel free to join our slack: https://rapidfortcommunity.slack.com for any issues you see with the project.

This will allow you to engage with us directly.

Thanks,
Vinod

**Comment by sylvainOL** [comment]
Hello @codervinod,

thanks for quick reply!

I'll engage with my security team to see if they're OK to use your images :)

Thanks!

**Comment by codervinod** [comment]
Hi @sylvainOL 

We talked to our core team and the way we will solve the auditing problem is by generating a hardening script. The script can run on Dockerfile to remove the unused components. Your security team can verify the script and ensure no RapidFort component is added to it.

Hope this helps. We are happy to get on a zoom call to ensure you can use these images.

Thanks,
Vinod
