### ISSUE TITLE
[Bug]: Postgresql image has no tzdata

### ISSUE THREAD

**Issue by ac130kz** [rapidfort/community-images#171]
### Name and Version

rapidfort/postgresql:latest

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [X] Docker Compose
- [X] Docker

### Is this issue reproducible on the original source image?

Not reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

RF error

### What steps will reproduce the bug?

Run the image with a custom timezone.

### Are you using any custom parameters or values?

Any non-UTC (default) timezone works. E.g.      POSTGRESQL_TIMEZONE: "Asia/Almaty"

### What is the expected behavior?

The `tzdata` packages should be installed to provide timezone data support.

### What do you see instead?

postgres-users  | 2022-09-27 08:48:50.530 GMT [1] LOG:  invalid value for parameter "TimeZone": "Asia/Almaty"

### Additional information

![2022-09-27T08:44:06UTC](https://user-images.githubusercontent.com/24586896/192479073-1e84f5a4-e662-4dd6-a087-eb301c357830.png)

**Comment by codervinod** [comment]
Thanks, @ac130kz, for reporting the issue. I will release a fix by today's end of the business day Pacific time zone.

**Comment by codervinod** [comment]
Here is the PR for the fix: https://github.com/rapidfort/community-images/pull/172 

This will be released tonight.

**Comment by codervinod** [comment]
@ac130kz This has been fixed and the image published on dockerhub.

```
docker sbom rapidfort/postgresql:latest | grep tzdata
Syft v0.46.3
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged packages      [38 packages]

tzdata         2021a-1+deb11u5               deb
```

Please let us know if you run into further issues. You can also join our community slack for more real-time discussions. https://rapidfortcommunity.slack.com/
