### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by rafalohaki** [rapidfort/community-images#174]
### Name and Version

arm support

### What is the problem this feature will solve?

arm support

### What is the feature you are proposing to solve the problem?

arm support

### What alternatives have you considered?

arm support

**Comment by codervinod** [comment]
Hi @rafalohaki,

We don't have arm support on the roadmap. When the RapidFort platform supports arm-based containers, we will add them to Community - images.

Thanks,
@codervinod

**Comment by rafalohaki** [comment]
ok

**Comment by codervinod** [comment]
if arm is a requirement, I would encourage you to join our slack: https://rapidfortcommunity.slack.com/ to have a discussion.

**Comment by rafalohaki** [comment]
bitnami recently added arm support for some of their docker images if not all

**Comment by baltazartroisville** [comment]
@codervinod I hope you don't mind me asking, but has something changed regarding your plans of not publishing arm images?
