### ISSUE TITLE
Appgate SDP k8s client

### ISSUE THREAD

**Issue by anoncam** [rapidfort/community-images#184]
### Name and Version

ghcr.io/appgate/charts/sdp-k8s-client:0.3.2

### What is the problem this image will solve?

enterprise networking

### Is this an open source project? Could you provide us more details about this project?

IDAM solution.  

### Which runtimes need to be supported for this image?

- [X] Kubernetes
- [ ] Docker Compose
- [ ] Docker

**Comment by codervinod** [comment]
@dreamer-nitj Could you please prioritize this image?

**Comment by dreamer-nitj** [comment]
@anoncam We have started to take a look at image hardening for the SDP k8s client and were trying to understand how is it used in the actual deployments. As per our understanding, it seems that an SDP controller and SDP gateway also needs to be setup before a SDP client can talk to the protected resources behind SDP gateway. Looking at the offering from Appgate https://www.appgate.com/support/software-defined-perimeter-support/sdp-v5-4 , it seems that these offerings needs a purchase. Is there any way to run the SDP controller & gateway without making a purchase?

**Comment by anoncam** [comment]
I have the elements required for testing. 

It will run as a sidecar and read a unique profile that's enabling the application to correlate entitlements to enable network routes. Basically a VPN. Happy to set up some time to look at this with you.

**Comment by randersson1000** [comment]
Cam its great that you have converged on an architecture, we should put an
architecture diagram in the presentation.

****

**Comment by ddooley77** [comment]
Hello @anoncam , I believe this was discussed outside of Git.  I'll move to close the issue.
