### ISSUE TITLE
Support confluentinc schema-registry-images

### ISSUE THREAD

**Issue by ChetanAtGNU** [rapidfort/community-images#231]
### Name and Version

rapidfort/confluent-schema-registry-images

### What is the problem this image will solve?

Fix vulnerabilities in confluent packages 
https://github.com/confluentinc/schema-registry-images/tree/master 

### Is this an open source project? Could you provide us more details about this project?

Yes 
https://github.com/confluentinc/schema-registry-images/tree/master

### Which runtimes need to be supported for this image?

- [X] Kubernetes
- [ ] Docker Compose
- [X] Docker

**Comment by ddooley77** [comment]
Thank you Chetan.  So you don't want zookeeper?

you want the latest of this?
 https://hub.docker.com/r/confluentinc/cp-schema-registry

**Comment by ddooley77** [comment]
Thanks, I will take a look.

**Comment by ddooley77** [comment]
Made available on
https://hub.docker.com/r/ddooley77/cp-schema-registry

If enough interest , we could make it part of community.



Use as you would the regular cp-schema-registry e.g.

replace schema-registry image confluentinc/cp-schema-registry:7.3.1 in docker-compose with image: ddooley77/cp-schema-registry:7.3.1-rfhardened

If folk have use of this I can make it more official.

Testing

tested with the avro example Confluent provides with a producer and a consumer.
tested the REST management API (registering a new schema, changing the compatibility mode etc.)
ran through some UI options (update schema, diff, change compatibility, checked messages on a topic etc.)
ran the compatibility test on an invalid schema , updated , and reran test
