### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ddominguezcorcoba** [rapidfort/community-images#235]
### Name and Version

rapidfort/postgresql:15.1, 15.1-debian-11, 15.1.0, 15.1.0-debian-11-r19, latest

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [X] Docker Compose
- [ ] Docker

### Is this issue reproducible on the original source image?

Reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

Coverage missing

### What steps will reproduce the bug?

POSTGRESQL_TIMEZONE=UTC

### Are you using any custom parameters or values?

POSTGRESQL_TIMEZONE=UTC

### What is the expected behavior?

2023-01-07 12:38:47.745 GMT [1] LOG:  database system is ready to accept connections

### What do you see instead?

postgresql 12:40:18.66 INFO  ==> ** Starting PostgreSQL **
2023-01-07 12:40:18.684 GMT [1] LOG:  invalid value for parameter "TimeZone": "UTC"
2023-01-07 12:40:18.684 GMT [1] FATAL:  configuration file "/opt/bitnami/postgresql/conf/postgresql.conf" contains errors
exited with code 1

**Comment by AnmolVirdi** [comment]
Thank you for pointing this out @ddominguezcorcoba. We have debugged this issue. Kindly check using rapidfort/postgresql:latest.
Now, We're resolving the other bug you've mentioned separately.

**Comment by ddominguezcorcoba** [comment]
I am afraid the issue is not entirely resolved.

When starting the container setting the (bitnami) environment variable POSTGRESQL_TIMEZONE set as:
- POSTGRESQL_TIMEZONE=UTC
the container complaints about an invalid value.
In order for this to work, UTC needs to be assigned as "UTC+0:00"

In any case, using the official JDBC driver is NOT possible, regardless whether the container is started with the POSTGRESQL_TIMEZONE set or not. I tried using the same nomenclature for setting driver properties, to no avail.
When using the original bitnami image, everything works as expected.

![image](https://user-images.githubusercontent.com/22766991/211772483-894610c4-1b12-4a3e-81ac-7ec2b2b63a97.png)

**Comment by AnmolVirdi** [comment]
Please use any of the latest tags. We have added fixes to them.
- rapidfort/postgresql:latest
- rapidfort/postgresql:15.1.0-debian-11-r20
- rapidfort/postgresql:15.1-debian-11
If these images already exist on your system, kindly remove them and pull again.

**Comment by AnmolVirdi** [comment]
We'll update other tags(older versions) asap. Please let us know if you need a particular image/tag to be fixed. We'll prioritize it.

**Comment by ddominguezcorcoba** [comment]
You are right, I just pulled the latest image and the time zone issue is no longer.

Thank you very much, Anmol.
--
Denis Domínguez Corcoba (Mr.)

On 11 Jan 2023, at 10:56, Anmol Virdi ***@***.***> wrote:



Please use any of the latest tags. We have added fixes to them.

  *   rapidfort/postgresql:latest
  *   rapidfort/postgresql:15.1.0-debian-11-r20
  *   rapidfort/postgresql:15.1-debian-11
If these images already exist on your system, kindly remove them and pull again.
