### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ddominguezcorcoba** [rapidfort/community-images#236]
### Name and Version

rapidfort/postgresql:15.1, 15.1-debian-11, 15.1.0, 15.1.0-debian-11-r19, latest

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [X] Docker Compose
- [ ] Docker

### Is this issue reproducible on the original source image?

Reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

Coverage missing

### What steps will reproduce the bug?

POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pgaudit,pg_stat_statements,pg_trgm,unaccent

### Are you using any custom parameters or values?

POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pgaudit,pg_stat_statements,pg_trgm,unaccent

### What is the expected behavior?

LOG:  database system is ready to accept connections

### What do you see instead?

2023-01-07 12:43:02.661 GMT [1] LOG:  pgaudit extension initialized
2023-01-07 12:43:02.662 GMT [1] FATAL:  could not load library "/opt/bitnami/postgresql/lib/pg_stat_statements.so": /opt/bitnami/postgresql/lib/pg_stat_statements.so: file too short
2023-01-07 12:43:02.662 GMT [1] LOG:  database system is shut down

### Additional information

When using the image docker.io/bitnami/postgresql, everything works as expected

**Comment by AnmolVirdi** [comment]
Hi @ddominguezcorcoba. Thank you for pointing this issue out. We have debugged it. Kindly check using any of the newly updated images:
- rapidfort/postgresql:latest
- rapidfort/postgresql:15.1
- rapidfort/postgresql:15.1.0-debian-11-r23
- rapidfort/postgresql:13.9.0-debian-11-r22
- rapidfort/postgresql:12.13.0-debian-11-r22
