### ISSUE TITLE
Add Docker tags always linking to latest non-major version

### ISSUE THREAD

**Issue by MatsG23** [rapidfort/community-images#243]
### Name and Version

rapidfort/mariadb:10.10

### What is the problem this feature will solve?

Having to look at the Docker page to see if there is a new minor version so you can update to it. You could set-up an auto-update script if you would not have to.

### What is the feature you are proposing to solve the problem?

It would be nice if there would be a tag like "10-current" that would get linked to the latest version of the 10 series of MariaDB (10.8, 10.9, now 10.10).

**Comment by codervinod** [comment]
Hi @MatsG23 we do have tolling tags which follow exact same pattern as rolling tags from bitnami. Could you please join our slack community to discuss further your requirements? I would be happy to get this resolved.
