### ISSUE TITLE
[mariadb] Setup root user as 'root'@'localhost' by default

### ISSUE THREAD

**Issue by MatsG23** [rapidfort/community-images#245]
### Name and Version

rapidfort/mariadb 10.10

### What is the problem this feature will solve?

By default, the container image sets up the root user as 'root'@'%' which means that every host can connect to the MySQL server with the root user. This is considered a security issue. `mysql_secure_installation` asks to disable remote root login on execution too.

### What is the feature you are proposing to solve the problem?

When creating the root user, create it as 'root'@'localhost'. This will improve the security because the administrator user can only be used on the system with the database server itself.

### What alternatives have you considered?

Of course, you can always edit the host of the root user to 'localhost' by yourself.
Alternatively, an environment variable (e.g. `MARIADB_DISABLE_REMOTE_ROOT_LOGIN`) could be added.

**Comment by codervinod** [comment]
Hi @MatsG23 , Could you please confirm if this is not the behavior in bitnami/mariadb images? RapidFort community images don't alter the behavior of source images. This issue seems to be requesting default behavior of source image.

**Comment by AnmolVirdi** [comment]
Hi @MatsG23, 
We've checked that the container image sets up the root user as 'root'@'% for both images (`rapidfort/mariadb` and `bitnami/mariadb`). If we add the feature suggested above, it would be image specific, beyond the process of creating a community image. 
Some might consider it a security issue while others might need it to work with every host. They can always edit the host of the root user to 'localhost' manually.
