### ISSUE TITLE
Use official NATS image rather than Bitnami variant

### ISSUE THREAD

**Issue by bruth** [rapidfort/community-images#257]
### Name and Version

rapidfort/nats 2.9.11

### What is the problem this feature will solve?

The `rapidfort/nats` image is based on the `bitnami/nats` image which is not the official image built from the NATS.io maintainers. The official image can be found [here](https://hub.docker.com/_/nats) and is also an official Docker Hub image.

If Rapidfort users are relying on your hardened NATS image, it should be based on the official image and not Bitnami's distribution. As one of the release managers of NATS, we keep up-to-date on CVEs found in dependencies and/or publish CVEs if discovered in NATS itself. We publish new releases as soon as any of these are discovered. Other copies/distributions of NATS will lag behind in releases and may introduce additional variation or issues within their distribution process. 

### What is the feature you are proposing to solve the problem?

Switch the `rapidfort/nats` image to use the official `nats` image.

**Comment by bruth** [comment]
(Also we just published 2.9.12 today)

**Comment by codervinod** [comment]
Hi @bruth Thanks for the feedback. Let us look into supporting nats official image.

**Comment by bruth** [comment]
Thanks @codervinod. Has any progress been made on this? I appreciate the attention.

**Comment by bruth** [comment]
I see that the `rapidfort/nats-official` image is available? I appreciate you adding that!
