### ISSUE TITLE
update wordpress

### ISSUE THREAD

**Issue by rafalohaki** [rapidfort/community-images#301]
### Name and Version

6.1-debian-11

### What is the problem this feature will solve?

there is  6.2.2 version of wordpress

### What is the feature you are proposing to solve the problem?

update

### What alternatives have you considered?

thank you

**Comment by AnmolVirdi** [comment]
Hi @rafalohaki,
Thanks for reaching out! We've updated WordPress:
- `rapidfort/wordpress:6.2.2-debian-11-r13`
https://hub.docker.com/r/rapidfort/wordpress
