### ISSUE TITLE
redis-cluster not latest?

### ISSUE THREAD

**Issue by lindeberg** [rapidfort/community-images#406]
### Name and Version

rapidfort/redis-cluster:latest

### What is the problem this feature will solve?

I'm new to RapidFort images and read that the goal is to be up-to-date with the original image versions within 24h. How come [redis-cluster 7.2.3](https://hub.docker.com/layers/bitnami/redis-cluster/7.2.3/images/sha256-28c18896974194f12c29e5e61d77d93e5c6107e3c46a44834285667d74c19569?context=explore) is not available yet?

### What is the feature you are proposing to solve the problem?

Provide the latest 7.2.3 version of bitnami/redis-cluster, instead of 7.2.1.

**Comment by AnmolVirdi** [comment]
Hi @lindeberg, there was some issue with tag updation which is fixed.
We have latest images for `reds-cluster` now:
[https://hub.docker.com/r/rapidfort/redis-cluster/tags](https://hub.docker.com/r/rapidfort/redis-cluster/tags)
- `7.2.4-debian-12-r9`
- `7.0.15-debian-12-r9`

Thanks,
Anmol
