### ISSUE TITLE
Add support for linux/arm64 arch

### ISSUE THREAD

**Issue by darkv** [rapidfort/community-images#585]
### Name and Version

all

### What is the problem this feature will solve?

Running any RapidFort images on Mac will run them in emulation mode.

### What is the feature you are proposing to solve the problem?

Build docker images for both archs, linux/amd64 _and_ linux/arm64, by using docker buildx.

**Comment by AnmolVirdi** [comment]
Hi @darkv,
This is in our roadmap. The team is working on adding support for `linux/arm64`.
