### ISSUE TITLE
[Bug]: Missing "pg_amcheck" functionality in rapidfort/postgresql-official

### ISSUE THREAD

**Issue by UdBe** [rapidfort/community-images#603]
### Name and Version

rapidfort/postgresql-official

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [ ] Docker Compose
- [X] Docker

### Is this issue reproducible on the original source image?

Not reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

RF error

### What steps will reproduce the bug?

1. Pull the rapidfort/postgres-official image
2. Run the image and use docker exec -it my_container bash to access the container terminal
3. Run the pg_amcheck command (used to check for corrupted databases)
4. Error message is thrown.

### Are you using any custom parameters or values?

`-e POSTGRES_PASSWORD=mypassword while running the docker image.`

### What is the expected behavior?

The pg_amcheck tool in PostgreSQL checks for corruption in one or more databases. The output of the pg_amcheck test includes a skip message if the index layout doesn't match expectations. This message includes the expected bytes and the found bytes.

### What do you see instead?

`bash: pg_amcheck: command not found`

**Comment by AnmolVirdi** [comment]
Hi @UdBe, can you please clarify which image tag was used on your end?

**Comment by UdBe** [comment]
I have used the following images:
- hardened image: rapidfort/postgresql-official:16.3-bookworm
- original image: postgres:16.3-bookworm

**Comment by Kirandeep-Singh-Khehra** [comment]
Hi @UdBe it seems that `pg_amcheck` is present in `rapidfort/postgresql-official:16.3-bookworm`.

You can run this for confirmation:
```bash
docker run -it --rm  rapidfort/postgresql-official:16.3-bookworm pg_amcheck --help
```

There might be some confusion between tags.

**Comment by UdBe** [comment]
Hi @Kirandeep-Singh-Khehra 

Yes there might be some confusion in the image name. I am able to reproduce this issue with the latest version of these images ( without specifying any tag )

- `docker pull postgres`
- `docker pull rapidfort/postgresql-official`

**Comment by UdBe** [comment]
![03c51660-bd81-4b45-9e00-cf022d92fa40](https://github.com/rapidfort/community-images/assets/71140717/680c6c84-8845-46c5-b289-50b99ea45f3a)

**Comment by Kirandeep-Singh-Khehra** [comment]
@UdBe There is a difference between versions. `postgres:latest` is at `16.3` but `rapidfort/postgresql-official` is at `12.18` and pg_amcheck is available only in versions 14+. [pg_amcheck doc here](https://www.postgresql.org/docs/current/app-pgamcheck.html)

> **Info:** `latest` tag might not always be latest.
