### ISSUE TITLE
[Bug]: listing databases without authentication in rapidfort/mongodb.

### ISSUE THREAD

**Issue by rinkydevi** [rapidfort/community-images#605]
### Name and Version

rapidfort/mongodb:7.0

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [ ] Docker Compose
- [X] Docker

### Is this issue reproducible on the original source image?

Reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

User error

### What steps will reproduce the bug?

1. Launch the [rapidfort/mongodb](https://hub.docker.com/r/rapidfort/mongodb) image.
2. Connect the container to the bash using ```docker exec -it mongo-container-main bash```.
3. Run the ```mongosh``` command.
4. Run ```show dbs``` command.

### Are you using any custom parameters or values?

```-e MONGO_INITDB_ROOT_USERNAME='root' ``` and ``` -e MONGO_INITDB_ROOT_PASSWORD='secret' ```  while launching the image.

### What is the expected behavior?

It should show ```MongoServerError[Unauthorized]: Command listDatabases requires authentication``` , because we are trying to access the database without any authentication .
![image](https://github.com/rapidfort/community-images/assets/82359874/2f6ac59d-a52c-4dc0-b7e7-1659d639a231)

### What do you see instead?

We get the list of databases instead of the error, even when trying to access it without any authentication.
![image](https://github.com/rapidfort/community-images/assets/82359874/67625308-0c1a-4e70-9e6f-3aaa54368e23)

**Comment by Kirandeep-Singh-Khehra** [comment]
Hi @rinkydevi , Can you please update us with image name and tag of images used in comparison on your end.

**Comment by rinkydevi** [comment]
Greetings @Kirandeep-Singh-Khehra  , i used rapidfort/mongodb:7.0 and mongo:latest for my comparison between these these two images

**Comment by Kirandeep-Singh-Khehra** [comment]
@rinkydevi There is little confusion here, Actually `rapidfort/mongodb` is based on `bitnami/mongodb` and `rapidfort/mongodb-official` is based on `mongo`. And this is followed for all images. You can crosscheck between these images and update if this issue is there or not.
