### ISSUE TITLE
[Bug]: Unable to persist/mount volumes in rapidfort/postgresql12-ib:latest

### ISSUE THREAD

**Issue by pranavSinha0** [rapidfort/community-images#606]
### Name and Version

rapidfort/postgresql12-ib:latest

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [ ] Docker Compose
- [X] Docker

### Is this issue reproducible on the original source image?

Reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

Coverage missing

### What steps will reproduce the bug?

1.  Pull the [rapidfort/postgresql12-ib:latest](https://hub.docker.com/r/rapidfort/postgresql12-ib)
2.  Run the container with a `mounted volume/ persistent flag`
 ```
 docker run -d \
  --name rapidfort-postgres \
  -e POSTGRES_USER=test \
  -e POSTGRES_PASSWORD=test \
  -e POSTGRES_DB=test \
  -p 5430:5432 \
  -v /path:/var/lib/postgresql/data \
  rapidfort/postgresql12-ib:latest
  ```

### Are you using any custom parameters or values?

  `-v /path:/var/lib/postgresql/data`
  
 Any path with persistent volume while starting the docker container

### What is the expected behavior?

- `Persitent volume` is supported in the postgres-12 image
- Docker container running [rapidfort/postgresql12-ib:latest](https://hub.docker.com/r/rapidfort/postgresql12-ib) should not immediately terminate after starting the container with the persistent volume

**_NOTE_**: This is the issue only if specifying a volume path (even though the src path of official postgres that is `/var/lib/postgresql/data` is correct)

### What do you see instead?

![image](https://github.com/rapidfort/community-images/assets/158028092/47d0b90a-4469-4be4-b179-1491a4563a8a)
This is logs of the container which runs [rapidfort/postgresql12-ib:latest](https://hub.docker.com/r/rapidfort/postgresql12-ib) this image after it immediately terminates

### Additional information

- NOTE: I have only tested this in `Windows` environment with docker desktop

**Comment by AnmolVirdi** [comment]
Hi Pranav,
`rapidfort/postgresql12-ib` is actually hardened version of `Postgresql12 Iron Bank` and not Official Postgres image from DockerHub.
