### ISSUE TITLE
[Bug]: `remsh` erlang shell not working in rapidfort/couchdb-official

### ISSUE THREAD

**Issue by utkarsh-1905** [rapidfort/community-images#610]
### Name and Version

rapidfort/couchdb-official:3.3.3

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [ ] Docker Compose
- [X] Docker

### Is this issue reproducible on the original source image?

Reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

RF Error

### What steps will reproduce the bug?

Run the container using `docker run -d --name rcdb-3 -p 5984:5984 -p 4368:4369 -e COUCHDB_SECRET=hello -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -e ERL_FLAGS="-setcookie brumbrum" rapidfort/couchdb-official:3.3.3` and then try entering the erlang shell using `docker exec -it rcdb-3 /opt/couchdb/bin/remsh`

### Are you using any custom parameters or values?

No

### What is the expected behavior?

![Screenshot from 2024-05-20 16-48-56](https://github.com/rapidfort/community-images/assets/83540694/4acad1b5-5009-49b4-879a-c605c0ab4379)

### What do you see instead?

`/opt/couchdb/bin/remsh: 131: exec: env: not found`

env command is not available in the container

### Additional information

The remsh shell is a utility used to connect with other nodes when couchdb is working in a cluster setup

**Comment by utkarsh-1905** [comment]
Rapidfort image => `rapidfort/couchdb-official:3.3.3`
Tested against => `couchdb:3.3`

**Comment by utkarsh-1905** [comment]
There is also a coverage error [here](https://github.com/rapidfort/community-images/blob/c579765a391669a93d1a15c021aea8ee698c2efc/community_images/couchdb/official/host_coverage.sh#L8) (in test script) since its only checking -h flag which is a bash script which runs fine, but the actual command does not run because of the missing `env` package

**Comment by AnmolVirdi** [comment]
Issue has been fixed and changes will show up in new `rapidfort/couchdb-official` images
