### ISSUE TITLE
[Bug]:  Missing Core FUNCTION Commands in rapidfort/redis-official

### ISSUE THREAD

**Issue by Ayush-Vashisht** [rapidfort/community-images#614]
### Name and Version

rapidfort/redis-official

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [X] Docker Compose
- [X] Docker

### Is this issue reproducible on the original source image?

Reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

RF error

### What steps will reproduce the bug?

1.Pull the latest Redis image from RapidFort: `docker pull rapidfort/redis-official:latest`
2.Run the Redis container:  `$ docker run -it --rm -p 6379:6379 rapidfort/redis-official:latest`
3.Connect to the Redis container: `docker exec -it <name-of-container> redis-cli`
4.Attempt to use any FUNCTION command, such as:  FUNCTION LIST, FUNCTION LOAD, FUNCTION DUMP

### What is the expected behavior?

The FUNCTION commands should execute successfully, performing the corresponding operations as per the Redis 7.0+ specification.

### What do you see instead?

None of the FUNCTION commands are recognized, resulting in error messages such as:
(error) ERR unknown command `FUNCTION`, with args beginning with: `LIST`,

### Additional information

I'm using Raoidfort's redis-official image and redis-official image.
Docker Version: 25.0.3
Operating System: Docker Desktop (which runs Docker containers within a Linux virtual machine)

**Comment by Kirandeep-Singh-Khehra** [comment]
Hi @Ayush-Vashisht, redis-cli in `redis:latest` image is of `7.2.4` and `latest` tag is copy of `7.2.4-bookworm`. And on other hand RapidFort's `rapidfort/redis-official:latest` is having redis-cli of version `6.0.20`. And  [FUNCTION docs](https://redis.io/docs/latest/develop/interact/programmability/functions-intro) says that FUNCTION is added in version 7. Hence its not availible in version 6.

Try to use tag name (other than latest).

Closing this issue/bug.
