### ISSUE TITLE
[Bug]: tls1.2 connections fails

### ISSUE THREAD

**Issue by rinkydevi** [rapidfort/community-images#615]
### Name and Version

rapidfort/curl : 8.7.1

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [ ] Docker Compose
- [X] Docker

### Is this issue reproducible on the original source image?

Reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

Source image error

### What steps will reproduce the bug?

1. Run curl in any linux flavour ``` curl -L -v --tlsv1.2 https://www.jio.com```. connection will be successful
2. launch docker image with command ```docker run --rm --name curl-rapid rapidfort/curl:8.7.1 -L -v --tlsv1.2 https://www.jio.com```.

### What is the expected behavior?

The connection should be successful as the website supports tls1.2 in curl .

### What do you see instead?

unsafe legacy renegotiation disabled , it should support tls1.2 as it is secure and around 45 percent of internet still runs on tls1.2 
![image](https://github.com/rapidfort/community-images/assets/82359874/48b3889a-9508-403f-b465-c1a5c07b4d29)

**Comment by Kirandeep-Singh-Khehra** [comment]
Hi @rinkydevi original source image for `rapidfort/curl:8.7.1` is `curlimages/curl:8.7.1`. and it runs in same way in my case using
```bash
docker run --rm --name curl-rapid curlimages/curl:8.7.1 -L -v --tlsv1.2 https://www.jio.com
```

Keeping this issue for some time before closing, please update us within this time.

**Comment by rinkydevi** [comment]
it is not supporting in curlimages/curl also , therefore reported it

**Comment by Kirandeep-Singh-Khehra** [comment]
@rinkydevi Thanks for your affirmation, RapidFort Community-Images focuses on removing redundant/unused files from docker images. And we are not currently fixing or adding functionality to any image.

Closing because tls v1.2 is also not supported in source/original image.
