### ISSUE TITLE
[Bug]: apt command not found in rapidfort/postgresql:16.3

### ISSUE THREAD

**Issue by rinkydevi** [rapidfort/community-images#623]
### Name and Version

rapidfort/postgresql:16.3

### Which runtime are you using to reproduce this issue?

- [ ] Kubernetes
- [ ] Docker Compose
- [X] Docker

### Is this issue reproducible on the original source image?

Reproducible

### Could you please identify the category? Details in TROUBLE_SHOOTING.md

Coverage missing

### What steps will reproduce the bug?

1. Run the postgres container by ```docker run -e POSTGRES_PASSWORD=password -d -p 5434:5432 rapidfort/postgresql:16.3```
2. Execute the container in sh terminal ```docker exec -it 9f50e1baa538 sh ```
3. run the ``` apt ``` command.

### Are you using any custom parameters or values?

```-e POSTGRES_PASSWORD=password``` ```-p 5434:5432 ```

### What is the expected behavior?

apt command should run as shown in the image below
![image](https://github.com/rapidfort/community-images/assets/82359874/e65e6e10-0aeb-41d7-8327-e4d07ae36282)

### What do you see instead?

apt command is not found
![image](https://github.com/rapidfort/community-images/assets/82359874/1ee2b54a-d84e-49ed-b84d-bd202d9dc5e9)

**Comment by Kirandeep-Singh-Khehra** [comment]
Rapidfort removes apt and all package managers from source images. To reduce the attach surfaces
