### ISSUE TITLE
Add RabbitMQ Image

### ISSUE THREAD

**Issue by scottd018** [rapidfort/community-images#93]
### Name and Version

rapidfort/rabbitmq:future

### What is the problem this feature will solve?

I happened to stumble across this project via browsing LinkedIn and it solves a good bit of the problems that I'm seeing in that:

1) Bitnami images are good, and have a lot of additional features, but...
2) They also pack a lot of bloat into the images, which becomes a problem in highly secure environments with strict security/compliance requirements.

I am working a project now that uses NGINX/RabbitMQ.  I see RabbitMQ is missing, but I do intend to use NGINX.

### What is the feature you are proposing to solve the problem?

Add a RabbitMQ image to the collection.

### What alternatives have you considered?

Use the Bitnami image or use the Alpine image.  The alpine image actually solves problems for us, but we have an internal policy that restricts their usage.

**Comment by codervinod** [comment]
Thanks @scottd018 , we will prioritize this issue. @dreamer-nitj can you look into it?

**Comment by codervinod** [comment]
Hi @scottd018 , We have added rabbitmq image. https://hub.docker.com/r/rapidfort/rabbitmq Please try it and let us know if you run into any issues. You can also join our slack to discuss any issues: https://join.slack.com/t/slack-ch72160/shared_invite/zt-1cafpzlyb-9I5He8olcp~FxmpZKxR~CA
